### ISSUE TITLE
VkResult vkEnumeratePhysicalDevices signature is...

### ISSUE THREAD

**Issue by hollandar** [terrafx/terrafx.interop.vulkan#37] opened 2021-03-29 12:22 UTC
#### Description (optional)

Calling this method with the default bindings and casting the last property to IntPtr* causes the pointer to the allocated memory to be overwritten, and a later access results in a violation.

#### Reproduction Steps

Call Vulkan.vkEnumerateDeviceExtensionProperties passing and IntPtr* marshalled from a VkExtensionProperties*.

#### Expected Behavior

Memory is populated with device extension properties pointers.

#### Actual Behavior

Allocated is not overwritten, resulting in the allocated device ref remaining zero.  Instead the pointer itself is overwritten, corrupting later calls that rely on the device ref.

Fixing the bindings by changing from:
`
        [DllImport("vulkan", ExactSpelling = true)]
        public static extern VkResult vkEnumeratePhysicalDevices([NativeTypeName("VkInstance")] IntPtr instance, [NativeTypeName("uint32_t *")] uint* pPhysicalDeviceCount, [NativeTypeName("VkPhysicalDevice *")] IntPtr* pPhysicalDevices);
`

to

`
        [DllImport("vulkan", ExactSpelling = true)]
        public static extern VkResult vkEnumeratePhysicalDevices([NativeTypeName("VkInstance")] IntPtr instance, [NativeTypeName("uint32_t *")] uint* pPhysicalDeviceCount, [NativeTypeName("VkPhysicalDevice *")] VkPhysicalDevice* pPhysicalDevices);
`

resolves the issue and the API can be successfully called as follows:

`
VkExtensionProperties* availableExtensions = stackalloc VkExtensionProperties[(int)extensionCount];
Vulkan.vkEnumerateDeviceExtensionProperties(
    physicalDevice,
    null,
    &extensionCount,
    availableExtensions
);
`

Is this a problem with the binding generation??

**Comment by tannergooding** [comment] 2021-03-29 15:24
Your issue is referring to two separate and unrelated functions: `vkEnumeratePhysicalDevices` and `vkEnumerateDeviceExtensionProperties`. Could you please clarify if the issue you are hitting impacts one or both and the code that allows the issue to be reproduced?

The below assumes that the issue was with `vkEnumeratePhysicalDevices` and you were trying to pass one of the enumerated devices to `vkEnumerateDeviceExtensionProperties`

In general, the bindings are correct. The `VkPhysicalDevice` struct is a helper type and is not guaranteed to be compatible with the underlying `VkPhysicalDevice` typedef defined in `C`. The actual definition in `C` ends up being `struct VkPhysicalDevice_T* VkPhysicalDevice;` and therefore is an opaque handle.

Because it is an opaque handle, the underlying signature for something like: `vkEnumeratePhysicalDevices` looks like: `VkResult vkEnumeratePhysicalDevices(VkInstance instance, uint32_t* pPhysicalDeviceCount, VkPhysicalDevice* pPhysicalDevices);` and is actually (when resolving all typedefs): `VkResult vkEnumeratePhysicalDevices(VkInstance_T* instance, uint32_t* pPhysicalDeviceCount, VkPhysicalDevice_T** pPhysicalDevices);`.

This means that the actual P/Invoke needs to take something that is compatible and consistent everwhere, which would either be some `struct VkInstance_T { /* empty */ }` where every API takes `VkInstance_T*`, or something more generic/general like `IntPtr` or `void*`. The "standard" in .NET has been to use `IntPtr` for opaque handles and so that is done here as well.

The correct usage of the API then looks something like:
```csharp
var instance = VulkanInstance;

uint physicalDeviceCount;
if (vkEnumeratePhysicalDevices(instance, &physicalDeviceCount, pPhysicalDevices: null) != VK_SUCCESS)
{
    throw new ExternalException();
}

var physicalDevices = stackalloc IntPtr[unchecked((int)physicalDeviceCount)];
if (vkEnumeratePhysicalDevices(instance, &physicalDeviceCount, physicalDevices) != VK_SUCCESS)
{
    throw new ExternalException();
}
```

This is because `vkEnumeratePhysicalDevices` effectively returns an array of physical device (Physical Device is `IntPtr`, so an array of them is `IntPtr*` with an associated `Count` parameter).

A more complete example, including creating a wrapper type might look like: https://source.terrafx.dev/#TerraFX.Graphics.Vulkan/Graphics/VulkanGraphicsProvider.cs,d34c3cb30fb39949,references

**Comment by tannergooding** [comment] 2021-03-29 15:26
I am open to providing helper functions that are more friendly/easy to use at the cost of additional overhead due to things like implicit pinning, or which do the unwrapping/casting required to ensure the data passed stays blittable.

This is not something which ClangSharp can currently determine or do automatically because there isn't the required metadata in the header files for this.

**Comment by hollandar** [comment] 2021-03-29 22:32
Great response, I had missed the fact that it was a collection of device ids, this makes perfect sense.I don’t think wrappers are strictly necessary, overhead to make alloc for the call is small anyway. Thanks for taking the time,Adrian.   From: Tanner GoodingSent: Tuesday, 30 March 2021 2:24 AMTo: terrafx/terrafx.interop.vulkanCc: Adrian Holland; AuthorSubject: Re: [terrafx/terrafx.interop.vulkan] VkResult vkEnumeratePhysicalDevices signature is... (#37) Your issue is referring to two separate and unrelated functions: vkEnumeratePhysicalDevices and vkEnumerateDeviceExtensionProperties. Could you please clarify if the issue you are hitting impacts one or both and the code that allows the issue to be reproduced?The below assumes that the issue was with vkEnumeratePhysicalDevices and you were trying to pass one of the enumerated devices to vkEnumerateDeviceExtensionPropertiesIn general, the bindings are correct. The VkPhysicalDevice struct is a helper type and is not guaranteed to be compatible with the underlying VkPhysicalDevice typedef defined in C. The actual definition in C ends up being struct VkPhysicalDevice_T* VkPhysicalDevice; and therefore is an opaque handle.Because it is an opaque handle, the underlying signature for something like: vkEnumeratePhysicalDevices looks like: VkResult vkEnumeratePhysicalDevices(VkInstance instance, uint32_t* pPhysicalDeviceCount, VkPhysicalDevice* pPhysicalDevices); and is actually (when resolving all typedefs): VkResult vkEnumeratePhysicalDevices(VkInstance_T* instance, uint32_t* pPhysicalDeviceCount, VkPhysicalDevice_T** pPhysicalDevices);.This means that the actual P/Invoke needs to take something that is compatible and consistent everwhere, which would either be some struct VkInstance_T { /* empty */ } where every API takes VkInstance_T*, or something more generic/general like IntPtr or void*. The "standard" in .NET has been to use IntPtr for opaque handles and so that is done here as well.The correct usage of the API then looks something like:var instance = VulkanInstance; uint physicalDeviceCount;if (vkEnumeratePhysicalDevices(instance, &physicalDeviceCount, pPhysicalDevices: null) != VK_SUCCESS){    throw new ExternalException();} var physicalDevices = stackalloc IntPtr[unchecked((int)physicalDeviceCount)];if (vkEnumeratePhysicalDevices(instance, &physicalDeviceCount, physicalDevices) != VK_SUCCESS){    throw new ExternalException();}This is because vkEnumeratePhysicalDevices effectively returns an array of physical device (Physical Device is IntPtr, so an array of them is IntPtr* with an associated Count parameter).A more complete example, including creating a wrapper type might look like: https://source.terrafx.dev/#TerraFX.Graphics.Vulkan/Graphics/VulkanGraphicsProvider.cs,d34c3cb30fb39949,references—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Closed** 2021-04-03 05:43 UTC
Labels: bug, untriaged
